### ISSUE TITLE
Update README.md documentation

### ISSUE THREAD

**Issue by RobLoach** [flathub/org.libretro.RetroArch#1]
Is there a Flathub standard put in place for README.md? Would be nice to update the documentation to talk about RetroArch and installing it with Flatpak through Flathub.

**Comment by TingPing** [comment]
I think these repos should be aimed at developers and not end users.

**Comment by Barthalion** [comment]
Yes, it's my fault I didn't rebase your changes on top of `new-pr` branch when merging. Feel free to drop it completely.

**Comment by RobLoach** [comment]
Stuck some initial docs over at https://github.com/flathub/org.libretro.RetroArch/pull/4 just to help clean it up. It's likely wrong, but a good start.
