### ISSUE TITLE
The build does not have wayland enabled.

### ISSUE THREAD

**Issue by i30817** [flathub/org.libretro.RetroArch#101]
From what i can see, my self-built RA starts with wayland gl context and the flatpak flathub 'stable' does not.

This wasn't always the case, until i *manually* updated 'wayland-protocols' package which was at '1.13-1' (or something) and failed to enable the feature.

I downloaded the deb to manually update to https://launchpad.net/ubuntu/+source/wayland-protocols/1.17-1 (because sudo apt-get update; sudo apt-get upgrade *wasn't upgrading the package for some unknown reason*)

Then my build could use wayland gl context and the udev error disappeared. And was much faster.

Resuming i think you should fix this unless you want people using wayland complaining about it being slow / broken.

Maybe you're building in a ubuntu buildbot (or debian i guess) and fell into the same problem? I don't know why the fuck that package wasn't upgrading automatically, but it sounds like something that would screw over a buildbot.

**Comment by RobLoach** [comment]
Glad you got it working! 

> Maybe you're building in a ubuntu buildbot

This flatpak is compiled on [Flathub](https://flathub.org/). This just asks for the wayland `--socket`.
