### ISSUE TITLE
Add Usage Documentation

### ISSUE THREAD

**Issue by ashak** [flathub/org.libretro.RetroArch#102]
Hi,

This is a brand new debian install with retroarch installed via flatpak.

The first thing I tried was to update the core info files. But in my terminal it tells me:

> [ERROR] Download of 'info.zip' failed: Write failed.

A quick strace later I see:

> [pid 1829] open("/app/share/libretro/info/info.zip", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 EROFS (Read-only file system).

Now /app doesn't exist and since the retroarch-with-flatpak documentation doesn't mention this i'm struggling to understand what's supposed to happen here. I don't expect that i'm supposed to create /app as a non root user on the system. So I wonder if some other magic is supposed to be in play here?

If I look at the retroarch.cfg file (from ~/.var/app/org.libretro.RetroArch/config/retroarch/retroarch.cfg) file I see a couple of different varieties of path:

```
assets_directory = "/app/share/libretro/assets/"
audio_filter_dir = "/app/lib/retroarch/filters/audio"
cheat_database_path = "/app/share/libretro/database/cht"
content_database_path = "/app/share/libretro/database/rdb"
content_favorites_path = "~/.var/app/org.libretro.RetroArch/config/retroarch/content_favorites.lpl"
content_history_path = "~/.var/app/org.libretro.RetroArch/config/retroarch/content_history.lpl"
content_image_history_path = "~/.var/app/org.libretro.RetroArch/config/retroarch/content_image_history.lpl"
content_music_history_path = "~/.var/app/org.libretro.RetroArch/config/retroarch/content_music_history.lpl"
content_video_history_path = "~/.var/app/org.libretro.RetroArch/config/retroarch/content_video_history.lpl"
core_assets_directory = "~/.var/app/org.libretro.RetroArch/config/retroarch/downloads"
cursor_directory = "/app/share/libretro/database/cursors"
input_remapping_directory = "~/.var/app/org.libretro.RetroArch/config/retroarch/config/remaps"
joypad_autoconfig_dir = "/app/share/libretro/autoconfig"
libretro_directory = "~/.var/app/org.libretro.RetroArch/config/retroarch/cores"
libretro_info_path = "/app/share/libretro/info"
overlay_directory = "~/.var/app/org.libretro.RetroArch/config/retroarch/overlay"
playlist_directory = "~/.var/app/org.libretro.RetroArch/config/retroarch/playlists"
rgui_config_directory = "~/.var/app/org.libretro.RetroArch/config/retroarch/config"
screenshot_directory = "~/.var/app/org.libretro.RetroArch/config/retroarch/screenshots"
thumbnails_directory = "~/.var/app/org.libretro.RetroArch/config/retroarch/thumbnails"
video_filter_dir = "/app/lib/retroarch/filters/video"
video_shader_dir = "/app/share/libretro/shaders"

```

The things starting with ~/.var/app.....  seem to be paths that exist and presumably anything referencing these work fine.

I wondered if /app in the others was supposed to be something that should have been replaced with ~/.var/app in some way (even if that were manually). But not all of the remainder of the paths starting with /app have matching (or similar) directories available under ~/.var/app.

If I take the last entry as an example /app/share/libretro/shaders... there's an almost matching ~/.var/app/org.libretro.RetroArch/config/retroarch/shaders
But if I look for something like /app/share/libretro/info, I can't find anything under ~/.var/app that's even remotely like it.

Which suggests to me that these things probably aren't expected to live under ~/.var/app at all.

I then looked in my users whole home directory and something like /app/share/libretro/assets/ seems to have something much more like a match under:
~/.local/share/flatpak/app/org.libretro.RetroArch/x86_64/stable/a437b0ef4eb1f1563d84a8ec881b9f19eb9fb84c06b35ecafe4ce85d5aad918a/files/share/libretro/assets
 
I looked at a few more and they also seem to have matching things under ~/.local/share/flatpak/app/org.libretro.RetroArch/x86_64/stable/a437b0ef4eb1f1563d84a8ec881b9f19eb9fb84c06b35ecafe4ce85d5aad918a/files

So I think I could probably fix my problem by simply replacing all references to /app in my retroarch.cfg with ~/.local/share/flatpak/app/org.libretro.RetroArch/x86_64/stable/a437b0ef4eb1f1563d84a8ec881b9f19eb9fb84c06b35ecafe4ce85d5aad918a/files

But I quickly realised that it seems silly that I should have to do that and would cause problems should ~/.local/share/flatpak/app/org.libretro.RetroArch/x86_64/stable/a437b0ef4eb1f1563d84a8ec881b9f19eb9fb84c06b35ecafe4ce85d5aad918a/files ever change.

Is there something with flatpak that i'm missing that should be doing this automatic translation of /app pathnames for me in some way? 

I've had a hunt around trying to work out if /app has some special meaning to flatpak, but so far have not managed to find anything useful.

Thanks

**Comment by ashak** [comment]
Further digging has led me [here](https://github.com/flatpak/flatpak/wiki/Filesystem):

> The files/ subdirectory contains the application files. Inside the sandbox, the files/ subdirectory gets mounted at /app, so the application should be built for the prefix "/app".

So I think my idea that some sort of magic should be happening is partially true?

Which suggests that this isn't happening for some reason? Or if it is, that it is mounted read  only for some reason?

**Comment by ashak** [comment]
Further searching has led me to [this issue](https://github.com/flatpak/flatpak/issues/545#issuecomment-278931352) where the op says:

> It is not possible for the app to write to /app or /usr, these are read-only mounts. The only place you can be sure to write is in the per-app directory in your homedir (~/.var/app/$appid).

Which seems to suggest that the retroarch config shouldn't point to things under /app at all if content updating is supposed to be used at all?

**Comment by RobLoach** [comment]
Correct, the .info files are shipped with the Flatpak, and are updated periodically through the Flatpak package.

Would like to disable Online Updater menu items for the things that are handled through Flatpak:
- Info files
- Assets
- Shaders
- Joystick Autoconfig
- etc

**Comment by ashak** [comment]
Oh I see. I hadn't realised that I was supposed to ignore the online updater.

Could some note be made on the [flatpak instructions on the retroarch site](https://www.libretro.com/index.php/retroarch-with-flatpak/) until the online updater is disabled? 

Or am I the only person dumb enough not to realise this was the case? :)

**Comment by RobLoach** [comment]
You do need the Online Updater for the cores, however.

**Comment by ashak** [comment]
Ah. Annoying.

**Comment by ashak** [comment]
Assuming there's a todo list somewhere with those tasks already on it, should I close this issue?

**Comment by RobLoach** [comment]
Let's just repurpose this one about adding docs about how to use it!
