### ISSUE TITLE
RetroArch crashes with .Platform, but works with .Sdk

### ISSUE THREAD

**Issue by gasinvein** [flathub/org.libretro.RetroArch#106]
Subj. `flatpak run org.libretro.RetroArch` causes RetroArch to crash immediately, but RetroArch launched via `flatpak run --runtime=org.kde.Sdk org.libretro.RetroArch` works fine. This is _not_ specific to #105 and reproducible with previous builds.

**Comment by RobLoach** [comment]
Strange. We were on `org.freedesktop.Platform` before, and switched to allow use of the Qt UI. Is there something we missed during that transition?

**Comment by gasinvein** [comment]
RetroArch as a Lutris extension works fine, runnting on FD.o .Platform. I can just guess there is something in FD.o runtime that is missing from KDE runtime.
Not sure how to debug it, since all debug tools are in the Sdk, and with Sdk the app works fine.

**Comment by stoofin** [comment]
Is this with the vulkan video driver? The libvulkan.so symlink went missing in org.kde.Platform 5.12, though it is present in the sdk.

**Comment by gasinvein** [comment]
@stoofin Indeed, adding a symlink `libvulkan.so` → `libvulkan.so.1` manually in the runtime fixes RetroArch.

**Comment by G-Ray** [comment]
I confirm when choosing vulkan driver retroarch does not even start with the default org.kde.Platform. Is this reported upstream ?

**Comment by orbea** [comment]
> Is this reported upstream ?

What is the correct org.kde.Platform issue tracker?

**Comment by RobLoach** [comment]
We've updated to org.kde.Platform 5.15-23.08. If this is still an issue, please feel free to re-open or make a new issue. Thanks all.
