### ISSUE TITLE
[Dolphin core] libudev.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by G-Ray** [flathub/org.libretro.RetroArch#115]
```sh
[ERROR] Failed to open libretro core: "path/to//dolphin_libretro.so"
[ERROR] Error(s): libudev.so.1: cannot open shared object file: No such file or directory
```

**Comment by realnc** [comment]
Same here on Gentoo Linux. Kind of disheartening to see flatpak having so many issues. It's supposed to be the "no hassle, no dependency hell, works everywhere" package format. At least that's the pitch. Well, apparently not :-/

**Comment by realnc** [comment]
Solved for me by running the flatpak RA binary outside of flatpak. See: https://github.com/libretro/RetroArch/issues/4664#issuecomment-510340394

**Comment by G-Ray** [comment]
@realnc It's not a "flatpak issue". This package's maintainers may just need to add more libraries to the build, here udev is missing. This should be a simple fix. They may not have time to test all the RetroArch cores to find specific issues.

So let's build a better RetroArch flatpak package together by reporting any issues we find, or by opening pull requests to fix issues.

**Comment by RobLoach** [comment]
Thought udev was in there already?
https://github.com/flathub/org.libretro.RetroArch/blob/master/org.libretro.RetroArch.json#L26

Perhaps it attempts to load the incorrect file? Is libudev.so there instead of libudev.so.1?

**Comment by TingPing** [comment]
The submodule we use only provides `libudev.so.0`, we would have to build `eudev` or `systemd`'s `udev` to get the newer version.

**Comment by RobLoach** [comment]
Thank you to @Makman2 for updating libudev here. Would you mind updating again and testing so we can confirm to close this one? Thanks!

**Comment by realnc** [comment]
Dolphin starts correctly now for me through flatpak.
