### ISSUE TITLE
Please update to 1.8.2, and wrong version 1.8.0 displayed on Flathub

### ISSUE THREAD

**Issue by David-Else** [flathub/org.libretro.RetroArch#132]
Hi, I am trying to get the latest version and the official download page says to get it from Flathub:

https://www.retroarch.com/?page=platforms

but it is an old version on Flathub.... I appreciate people are probably on holiday right now, but I hope it gets updated as soon as people are free.

Also right now it says the wrong version on Flathub, 1.8.0 is shown, but the change list here on Github says 1.8.1

Thanks :)

**Comment by RobLoach** [comment]
Thanks! Open to Pull Requests for it. I'll have time to look at this in the next couple days if anyone doesn't get to it before then.
