### ISSUE TITLE
sh: xrandr: command not found

### ISSUE THREAD

**Issue by lixoman100** [flathub/org.libretro.RetroArch#139]
Running RetroArch in verbose mode on MX Linux, latest version, installed from flatpak, I get the message ``sh: xrandr: command not found`` on the logs when trying to use switchres for CRT TVs.

The command xrandr is, in fact, available on my computer and I can use it on the console with no problems. I assume that RetroArch's incapability to use it is due to flatpak's sandboxing, but I could be wrong.

Is there a simple workaround I'm missing?

**Comment by lixoman100** [comment]
Note: I managed to make it work by doing:

``ln -s /usr/bin/xrandr /var/lib/flatpak/app/org.libretro.RetroArch/current/active/files/bin``

And switchres is now working, but this is an incredibly ugly hack and probably not a proper fix.

**Comment by RobLoach** [comment]
@lixoman100 Mind testing this build? https://github.com/flathub/org.libretro.RetroArch/pull/140

**Comment by lixoman100** [comment]
@RobLoach on that build xrandr worked fine without the hack.

I went to stable to ensure I didn't mess it up and it doesn't work there, so the test version seems to be fixed on its own.

**Comment by RobLoach** [comment]
Thanks! Merged that forwards.

**Comment by lixoman100** [comment]
Thank you, I'll report back once I get the update on stable to let you know if it is fixed there.

**Comment by lixoman100** [comment]
@RobLoach the stable branch got the update and I verified that xrandr is working properly on stable as well. Let me know if you need any further testing; otherwise, feel free to close the issue.

Thanks for the assistance!

**Comment by RobLoach** [comment]
Thanks a lot!
