### ISSUE TITLE
Joypad/gamepad controllers not working with udev from Linux Mint 19.3 and KDE Neon

### ISSUE THREAD

**Issue by candrapersada** [flathub/org.libretro.RetroArch#141]
why joypad auto configuration not working for flathub. ubuntu based?

**Comment by RobLoach** [comment]
It's using the SDL input driver, which has less definitions. Had troubles getting udev permissions to work.... Mind trying a few of the other input drivers and sharing your experience?

**Comment by candrapersada** [comment]
how to get udev permission for Flathub user?

**Comment by RobLoach** [comment]
Thanks for testing! Tried getting udev to work a few times, no success....

In the mean time, feel free to save new SDL autoconfigs to:
https://github.com/libretro/retroarch-joypad-autoconfig

**Comment by candrapersada** [comment]
but why RetroArch from flathub autoconfig save to
`/app/share/libretro/autoconfig`?
and error saving autoconfig file.

**Comment by RobLoach** [comment]
Ah yes, because it's a shared folder. You'll have to change the permissions of the folder.

**Comment by candrapersada** [comment]
how to change the permissions of the folder?

**Comment by candrapersada** [comment]
and why not found folder
`/app/share/libretro/autoconfig`
from
![File root](https://user-images.githubusercontent.com/36833664/73141439-923e3f80-40b6-11ea-9550-202d1c10758f.png)

**Comment by RobLoach** [comment]
Flatpak wraps the directories. Should be somewhere in....

~/.local/share/flatpak/app/og.libretro.RetroArch

**Comment by candrapersada** [comment]
but why use /app/share/libretro/autoconfig
not  ~/.local/share/flatpak/app/og.libretro.RetroArch or ~/.var/app/org.libretro.RetroArch, create error saving autoconfig file.?
and how to how to get the permissions of the folder for save new SDL autoconfigs?

**Comment by RobLoach** [comment]
RetroArch ships a few folders that come with configs. The PPA has a similar problem. Flatpak handles those directories. You can just chmod it, and it'll write to it correctly.

**Comment by candrapersada** [comment]
how to use chmod for change the permissions of the folder for save new SDL autoconfigs?

**Comment by RobLoach** [comment]
You could probably change the autoconfig directory, and then save it in a different directory.

**Comment by candrapersada** [comment]
but why default settings use,
/app/share/libretro/autoconfig for RetroArch from flathub?

**Comment by candrapersada** [comment]
and add ~/.var/app/org.libretro.RetroArch/config/retroarch/saveconfig only for save new setting Joypad/gamepad Manually

**Comment by RobLoach** [comment]
Because autoconfigs are installed files. We can't ship files directly into a user's writable config directory. You can see how FLATPAK_DEST is used in:
https://github.com/flathub/org.libretro.RetroArch/blob/master/org.libretro.RetroArch.json
