### ISSUE TITLE
why update retroarch-joypad-autoconfig to flathub slow?

### ISSUE THREAD

**Issue by candrapersada** [flathub/org.libretro.RetroArch#144]
why update retroarch-joypad-autoconfig to flathub slow?
https://github.com/libretro/retroarch-joypad-autoconfig/pull/612#issuecomment-593519444

**Comment by RobLoach** [comment]
It's done manually. Feel free to submit a Pull Request with the update if you'd like it done. I usually do it when a RetroArch tag is made.

**Comment by candrapersada** [comment]
why for install retroarch from Flatpak
must use `/app/share/libretro/autoconfig`

**Comment by RobLoach** [comment]
Becuase it installs the autoconfig files there... Here is how to update it: https://github.com/flathub/org.libretro.RetroArch/pull/145
