### ISSUE TITLE
Joypad is not responsive

### ISSUE THREAD

**Issue by RobLoach** [flathub/org.libretro.RetroArch#153]
- SDL2 Joypad is functional, but program is jumpy
- All other joypad input drivers arn't functional

udev won't be getting good support for flatpak soon. We'll have to figure out a cleaner way around it.

**Comment by alexb3d** [comment]
Just yesterday I reported this error in the wrong place.
The jstest program also in flatpak works correctly.
https://github.com/libretro/retroarch-joypad-autoconfig/issues/643

**Comment by 1h8me2** [comment]
I can confirm that I also experience this issue. I am running Fedora 32. With the Retroarch flatpak I can not get wired or bluetooth controllers to get recognized. I tested other flatpak apps like Dolphin and Citra and they recognize both controllers immediately. I also installed the RetroArch package from DNF to test and it does pick up the controllers as well. This is specific to the RetroArch flatpak.

**Comment by RobLoach** [comment]
Would you mind doing some testing with the other joypad input drivers? I've only been able to use SDL2, but when using SDL2 joypad driver, the application intermittedly stalls.

**Comment by alexb3d** [comment]
Tested with a wired Xbox360 controller.

udev, does not show control

linuxraw, it shows the name of the control and the assigned buttons but they don't work, they can be assigned manually and it works (but the crosshead doesn't work in the menu)

parport, displays a generic control and buttons cannot be assigned

sdl2, works normally, shows the name of the control, the assigned buttons and everything works

hid doesn't work, it hangs when i restart retroarch

**Comment by RobLoach** [comment]
Thanks for the testing!!!

> linuxraw, it shows the name of the control and the assigned buttons but they don't work, they can be assigned manually and it works (but the crosshead doesn't work in the menu)

linuxraw may be an option then. It is missing A LOT of the autoconfigs, so we'll have to define those across a bunch of controllers.

> sdl2, works normally, shows the name of the control, the assigned buttons and everything works

When using SDL, does the application get laggy? I've seen that happen, and gotten reports of it too.

**Comment by 1h8me2** [comment]
Could this be a udev rule permission issue? I looked over the settings from the DNF package install of RetroArch and compared it to the Flatpak and they are using the same default driver settings.

**Comment by 1h8me2** [comment]
I can confirm that switching the joypad driver to sdl2 fixes my controller issue. It is set to udev by default, much like the normal repository version does but for some reason it no longer works in the flatpak. I would assume it is a udev rule permission issue.

**Comment by alexb3d** [comment]
I have been testing some games, for approximately three hours, of nes, snes, genesis, n64 and Dreamcast with SDL2 and it works perfect, rawlinux also works perfect.
I have not tested with other controls, tomorrow I do a test of two players and "rare" controls.

What are the error reports? I want to try to reproduce them.

**Comment by RobLoach** [comment]
Think we should siwtch to `rawlinux` instead of SDL?

**Comment by alexb3d** [comment]
I am using SDL and it works fine, I have had no problem. Very short days, trying something new or experiments with the Flycast textures.

Recently, for my nephews, I installed 4 controls. 1 Xbox, 2 arcade PSX (with adapter) and 1 PSX clone (USB). Multiplayer with MAME. I played little but it gave me no problems.

It seems to me that SDL is working fine, but if you prefer to use rawlinux then tell me how can I help you configure those things.

**Comment by RobLoach** [comment]
Updated in https://github.com/flathub/org.libretro.RetroArch/pull/156 ... THANKS!

**Comment by soredake** [comment]
Is there upstream flatpak issue about udev not working?

**Comment by RobLoach** [comment]
The closest I've found is this older discussion on GitLab and this one...  https://github.com/flatpak/flatpak/issues/961

**Comment by RobLoach** [comment]
SDL seems to work though.

**Comment by RobLoach** [comment]
While I haven't been able to reproduce the issue, others may? Thanks for the testing.
