### ISSUE TITLE
Can't find info directory

### ISSUE THREAD

**Issue by obbardc** [flathub/org.libretro.RetroArch#165]
I want to add my own core, so I add the .so file under `$HOME/.var/app/org.libretro.RetroArch/config/retroarch/cores/`, but can't seem to find the `info` directory to add the core information file ?

thanks!

**Comment by RobLoach** [comment]
Installs the assets files to the share/libretro folder... For me....

```
~/.local/share/flatpak/app/org.libretro.RetroArch/current/active/files/share/libretro/info
```
