### ISSUE TITLE
RetroArch closes with the Threaded Video option. driver gl and glcore 

### ISSUE THREAD

**Issue by alexb3d** [flathub/org.libretro.RetroArch#170]
RetroArch closes when activating or deactivating the Threaded Video option, with the gl and glcore drivers activated, with Vulkan it works fine.

In the PPA version it is activated without problems, when it is deactivated RetroArch closes.
It is a similar problem, I already made the report [here](https://github.com/libretro/RetroArch/issues/12245)

RetroArch 1.9.1 / Ubuntu 20.04.2 / Core i7 3770 / Intel® HD Graphics 4000 (IVB GT2)

**Comment by RobLoach** [comment]
I saw an update in 1.9.6 refer to this. May be fixed.

**Comment by alexb3d** [comment]
It is working perfect in the versions that I have and with all the video drivers.
Thank you!
