### ISSUE TITLE
Build some cores

### ISSUE THREAD

**Issue by RobLoach** [flathub/org.libretro.RetroArch#18]
Having some cores built would be nice. There could be an issue with distribution, so we should only ship permissive cores.

**Comment by RobLoach** [comment]
https://github.com/flathub/org.gnome.Games/tree/master/libretro-cores

**Comment by TingPing** [comment]
It is needed for gnome-games because it doesn't have a downloader. I sort of think the current situation isn't too bad.

**Comment by RobLoach** [comment]
I agree.... Having to download the cores manually for RetroArch makes sense. Sometimes it's annoying to have to download them though. Let's keep this open for now, and see if others chirp in. Thanks!

**Comment by RobLoach** [comment]
Going to close this one for now.
