### ISSUE TITLE
missing dependency libaio.so

### ISSUE THREAD

**Issue by toussii** [flathub/org.libretro.RetroArch#186]
When openening the pcsx2 core the following error is displayed in the log:
`[ERROR] Error(s): libaio.so.1: cannot open shared object file: No such file or directory`
This makes it impossible to use the pcsx2 core  with the flatpak package.

**Comment by flibitijibibo** [comment]
Build instructions, taken and updated from https://github.com/flatpak/flatpak/issues/2806 :

```
{
  "name": "libaio",
  "config-opts": [
    "--buildtype=debugoptimized"
  ],
  "buildsystem": "simple",
  "build-commands": [
    "make prefix=$FLATPAK_DEST install"
  ],
  "sources": [
    {
      "type": "git",
      "url": "https://pagure.io/libaio.git",
      "tag": "libaio-0.3.112",
      "commit": "d025927efa75a0d1b46ca3a5ef331caa2f46ee0e"
    }
  ]
}
```

**Comment by RobLoach** [comment]
Excellent! Thanks a lot, Ethan. Complaining about libGLU now....
```
[ERROR] Error(s): libGLU.so.1: cannot open shared object file: No such file or directory
```

Might be a good idea to consider statically compiling those, but I'm unsure how viable that is.

**Comment by flibitijibibo** [comment]
I'm surprised that's not part of the freedesktop SDK - it may be worth filing a report for 
org.freedesktop.Platform.GL? It's apparently in the NV variant: https://github.com/flathub/com.valvesoftware.Steam/issues/61

**Comment by tinywrkb** [comment]
@flibitijibibo 

> ```
>   "config-opts": [
>     "--buildtype=debugoptimized"
>   ],
>   "buildsystem": "simple",
> ```

This is wrong, `config-opt` suggests that the build system has a configure step, which is not true for the `simple` build system type.

I also recommend avoiding using git source type if possible in order to make use of `flatpak-external-data-checker` which currently doesn't support reading timestamps from git repos.

I recommend doing something like this

```
{
  "name": "libaio",
  "no-autogen": true,
  "sources": [
    {
      "type": "archive",
      "url": "https://pagure.io/libaio/archive/libaio-0.3.112/libaio-libaio-0.3.112.tar.gz",
      "sha256": "b7cf93b29bbfb354213a0e8c0e82dfcf4e776157940d894750528714a0af2272"
    }
  ]
```

**Comment by RobLoach** [comment]
With https://github.com/flathub/org.libretro.RetroArch/pull/187 , the content loads, but doesn't run anything. I'm unsure what's wrong. Nothing clear in the loads. Shows that firmware status, content loaded, and then unloads the core :shrug:

**Comment by tinywrkb** [comment]
Starting retroarch with verbose output gives this message

```
[INFO] [Environ]: GET_VARIABLE pcsx2_upscale_multiplier: not implemented.
Segmentation fault (core dumped)
```

**Comment by tinywrkb** [comment]
Maybe we can get more info about this with `flatpak-coredumpctl`, but I'm gonna have to leave this for another day.  
Symbols are in the Debug extension, but as the core is downloaded and not being built by Flatpak, then we won't have symbols for it, only for what was built by Flatpak.

**Comment by RobLoach** [comment]
PPSSPP and RLVM are running here with the latest updates.
