### ISSUE TITLE
Request: Add StartupWMClass=retroarch to org.libretro.RetroArch.desktop file

### ISSUE THREAD

**Issue by GiantEnemyCrab** [flathub/org.libretro.RetroArch#191]
In Budgie Desktop Environment, in order to pin application to Icon Task List dock, I think it depends on `.desktop` file having `StartupWMClass` being present. (Reference: https://github.com/solus-project/budgie-desktop/issues/750)

I experimented with changing the .desktop file directly in `/var/lib/flatpak/exports/share/applications/org.libretro.RetroArch.desktop` and it worked very well. With `StartupWMClass=retroarch` added, it looks like below (just that one line was added):
```
[Desktop Entry]
Version=1.0
Name=RetroArch
GenericName=Frontend for the libretro API
Type=Application
Comment=Frontend for emulators, game engines and media players
Comment[ru]=Графический интерфейс для эмуляторов, игровых движков и медиаплееров
Comment[fr]=Interface graphique pour émulateurs, moteurs de jeu et lecteurs multimédia
Comment[de]=Front-End für Emulatoren, Spiel-Engines und Mediaplayer
Icon=org.libretro.RetroArch
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=retroarch org.libretro.RetroArch
Terminal=false
StartupNotify=false
Keywords=multi;engine;emulator;xmb;
Categories=Game;Emulator;
StartupWMClass=retroarch
X-Flatpak-RenamedFrom=retroarch.desktop;
X-Flatpak=org.libretro.RetroArch
```

I was seeing something like [yuzu flatpak desktop-file-edit command](https://github.com/flathub/org.yuzu_emu.yuzu/blob/bef7dd1a234120398f991089abf5cc69c3a05b13/org.yuzu_emu.yuzu.json#L204), which could be additional reference.

**Comment by RobLoach** [comment]
This is a great idea. Mind trying adding that in a Pull Request?

**Comment by GiantEnemyCrab** [comment]
@RobLoach Does this make it easier if this addition is applied in [upstream retroarch](https://github.com/libretro/RetroArch)?

**Comment by RobLoach** [comment]
Seems like a good thing to push upstream too 👍

**Comment by GiantEnemyCrab** [comment]
@RobLoach This has been merged upstream. I guess that mean when retroarch upgrades next time, the change will be automatically cascaded to downstream here such that no work is required?

**Comment by RobLoach** [comment]
Nice work! We can try it out on the next update, and if it doesn't take, we could add the flatpak script workaround.

**Comment by GiantEnemyCrab** [comment]
Upstream 1.9.8 is released and StartupWMClass addition is noted https://www.libretro.com/index.php/retroarch-1-9-8-released.
Is this change visible when releasing for flatpak?

**Comment by GiantEnemyCrab** [comment]
I confirmed this working, after updating retroarch to 1.9.8 from flathub.
Thank you for your kindness to listen to me on this, and very happy that this worked.
I will go ahead and close this. Thanks again!
