### ISSUE TITLE
1.10.0 window decorations on gnome wayland?

### ISSUE THREAD

**Issue by fishxz** [flathub/org.libretro.RetroArch#214]
hey,
with version 1.10.0 retroarch implemented https://github.com/libretro/RetroArch/pull/13397, but i still have no window decorations.

**Comment by RobLoach** [comment]
It's on KDE so that we have the Window GUI. Does KDE conflict with Wayland? Don't have a Wayland build right now to test.

**Comment by fishxz** [comment]
just noticed libdecor supporter got added later to this flatpak and the build on flathub probably doesn't have it. Will report later.

**Comment by RobLoach** [comment]
Thanks so much for the testing, @fishxz.

**Comment by fishxz** [comment]
can confirm it works now
