### ISSUE TITLE
Streaming and recording crash

### ISSUE THREAD

**Issue by DarkSide1305** [flathub/org.libretro.RetroArch#224]
Whenever I try to stream locally or simply just record Gameplay RetroArch immediately crashes. FFMPEG Support is installed and displayed as "Yes", but the logs show an error. Trying to stream does not cause an error, but recording does, the error being "[ERROR] [FFmpeg]: Cannot find vcodec libx264.". I got RetroArch via Discovery on my Steam Deck, and another person also has the exact same error on a Steam Deck aswell, so both of us concluded its likely the Flatpak that currently has the issue.

**Comment by RobLoach** [comment]
I think this is fixed with the change to webm... Unsure about streaming though. Feel free to re-open if it's still crashing.
