### ISSUE TITLE
Add 32bit build

### ISSUE THREAD

**Issue by RobLoach** [flathub/org.libretro.RetroArch#237]
Have a 32bit build of the Flatpak. A request from @littlemac123 over at https://github.com/libretro/RetroArch/issues/14597 .

**Comment by tinywrkb** [comment]
There are no 32bit runtimes, and last time I checked, Freedesktop;s maintainer said they are not coming back, so you can't provide a **separate** i386 variant, or should I say not anymore.  
There are `.Compat.i386` extensions for running 32bit binaries with the `x86_64` runtimes, but this won't help users with i386 distros.
