### ISSUE TITLE
Current Flatpak version is mismatched with the newest stable version

### ISSUE THREAD

**Issue by DisAccount** [flathub/org.libretro.RetroArch#248]
The newest stable downloaded from retroarch.com reports its Git version as 1581ece, while the Flatpak package's Git version is 6616b80. These two builds can't do netplay with each other, so it appears their functionality is different somewhere.

**Comment by RobLoach** [comment]
I think we did this already? https://github.com/flathub/org.libretro.RetroArch/commit/717b78093797270877ec416e58082f1c71d435d8

I could be wrong. Perhaps Flathub hasn't rebuilt it yet? The Release could be old. I'll do a double take

**Comment by DisAccount** [comment]
I did some digging myself and while the Flatpak version did receive a hotfix on March 16th, it is based on a commit one day older than the stable from the website.

**Comment by RobLoach** [comment]
Looks like the commit that was tagged as 1.15.0 caused some warnings in the build, but doesn't actually break anything.
