### ISSUE TITLE
Update to 1.16.0.3

### ISSUE THREAD

**Issue by RawToast225** [flathub/org.libretro.RetroArch#257]
My steam deck has RetroArch installed through EmuDeck. That version (flathub) and the Discover store version (also flathub) don't seem to run refreshes like other programs do.

The problem is that the current version has a bug where it uses D-Pad inputs after messing around in the quick menu. This bug is preventing me from playing a patched version of Majora's Mask because I need to redo the scaling setting every time I launch the game. When I go back to the game from the menus, the D-Pad inputs are overriding the left joystick inputs.

That bug has already been patched upstream on at least 1.16.0.2.

**Comment by RobLoach** [comment]
Didn't see the release, thanks a lot :+1:

**Comment by RawToast225** [comment]
Oh, dang! Really fast turn-around, thank you very much!
