### ISSUE TITLE
Using retroarch command returns error after uninstalling

### ISSUE THREAD

**Issue by PMCJTM** [flathub/org.libretro.RetroArch#262]
After uninstalling the flatpak version of RetroArch, attempting to run the command returns this

```
error: app/org.libretro.RetroArch/x86_64/master not installed
```

**Comment by RobLoach** [comment]
If you uninstall retroarch, it makes sense that it isn't installed anymore. Could you expand on what you're trying to do?

**Comment by PMCJTM** [comment]
My bad entirely, this was more an issue with my setup and something I forgot I configured

**Comment by RobLoach** [comment]
Glad you figured it out. I hope to update to dependencies here sometime too.
