### ISSUE TITLE
Wayland: Cannot load Shaders

### ISSUE THREAD

**Issue by matheuswillder** [flathub/org.libretro.RetroArch#275]
Full log attached at the end. As the title says, I have some global settings for shaders but after updating RetroArch some days ago they no longer work. When going directly to Quick Menu>Shaders>Load, none of the I try to load work either. I also tried download the shaders directly from libretro/slang-shaders repository and load/apply but got the same result. I also tried changing the video driver (from glcore to gl), but with gl when loading a shader I get a completely black screen.

In the log (using glcore as video driver), the lines related to trying to load/apply any shader appear to be the follows:

> [ERROR] [slang]: Invalid #pragma parameter line: "#pragma parameter shadowMask "shadowMask" 1.0 0.0 4.0 1.0".
> [INFO] [slang]: Compiling shader: "/app/share/libretro/shaders/shaders_slang/crt/shaders/fakelottes.slang".
> [ERROR] [slang]: Invalid #pragma parameter line: "#pragma parameter shadowMask "shadowMask" 1.0 0.0 4.0 1.0".
> [ERROR] [GLCore]: Failed to compile shader: "/app/share/libretro/shaders/shaders_slang/crt/shaders/fakelottes.slang".
> [ERROR] [GLCore]: Failed to create preset: "/app/share/libretro/shaders/shaders_slang/crt/fakelottes.slangp".
> [ERROR] [GLCore]: Failed to create filter chain: "/app/share/libretro/shaders/shaders_slang/crt/fakelottes.slangp". Falling back to stock.

I don't have too much free time to test other things right now, like test the compiled version offered in the libretro buildbot, but if you need any additional information to identify the problem, please let me know and I'll try to get it as soon as possible.

[retroarch.log](https://github.com/flathub/org.libretro.RetroArch/files/13949331/retroarch.log)

Edit: looking at the latest commits now, apparently what was updated in the last few days was not a new version of RetroArch but rather some dependencies. So just to clarify, I've been having this problem since the updates were made about 2 days ago, not since the last version of RetroArch that was released months ago.

**Comment by RobLoach** [comment]
Thanks for the report. Likely some change in org.platform.KDE's opengl? Will need to investigate

**Comment by RobLoach** [comment]
Shaders seem to be working for me in glcore with the shaders update https://github.com/flathub/org.libretro.RetroArch/pull/276

Though they were working for me before too, so I'm not sure what's wrong.

**Comment by RobLoach** [comment]
Thanks for the update. Glad shaders are working. I'm not quite sure how Wayland support is across platforms, but it does seem to be improving.

**Comment by unmacaque** [comment]
Just noticed that shaders have stopped working for me for a few weeks. Used to work fine before.

I am using "vulkan" driver. Other than that, same problem as the original post. See the attached log for my system specs: [retroarch.log](https://github.com/flathub/org.libretro.RetroArch/files/14156447/retroarch.log)

Would love to see a fix that does not involve switching the windowing system.

If there is something I can try, please let me know.

**Comment by RobLoach** [comment]
My only guess is shaders being not that well supported under integrated graphics and Vulkan/Wayland? Perhaps try the glcore again?

**Comment by RobLoach** [comment]
Shaders seem to be working for me with the latest update on glcore.

**Comment by RobLoach** [comment]
Thanks a lot for going through testing. It's likely wayland that's causing an issue. I'll ask a few of the other RetroArch devs.

**Comment by silver246** [comment]
This might be a similar issue to this one [here](https://github.com/libretro/RetroArch/issues/15756).

If the issue is caused by the locale of the user, starting RetroArch with `LANG=en_US.UTF-8 flatpak run org.libretro.RetroArch` might help. There is also a [fix](https://gitlab.freedesktop.org/libdecor/libdecor/-/merge_requests/132) for this in libdecor version 0.2.1. Updating the library to the newest version should fix this bug.

**Comment by RobLoach** [comment]
Looks like kowalski7cc updated it in shared-modules over at https://github.com/flathub/shared-modules/pull/288
