### ISSUE TITLE
dbus issue

### ISSUE THREAD

**Issue by davidhedlund** [flathub/org.libretro.RetroArch#285]
* Run this in the terminal: `$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=retroarch org.libretro.RetroArch -L pcsx2_libretro.so game.iso`
* Press Ctrl+C

Output:
```
dbus[2]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file ../../dbus/dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
```

The dbus issue is preventing me from generating a default .opt file by running the above command in combination with `timeout`: `$ timeout 10 /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=retroarch org.libretro.RetroArch -L pcsx2_libretro.so game.iso` that I'm running from a script.

Best

**Comment by davidhedlund** [comment]
* https://github.com/libretro/LRPS2/issues/278

**Comment by RobLoach** [comment]
CTRL-C sends an interrupt SIGINT to the application, forcing it to close. To quit the application, either close the window, or select the quit button.

**Comment by davidhedlund** [comment]
> To quit the application, either close the window, or select the quit button.

It's not possible since I run it from a script (needed to generate the .opt file that I then modify). So can you please re-open this issue?

**Comment by davidhedlund** [comment]
Generates ~/.var/app/org.libretro.RetroArch/config/retroarch/config/LRPS2/LRPS2.opt:
```
timeout 2 /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=retroarch org.libretro.RetroArch -L ~/.var/app/org.libretro.RetroArch/config/retroarch/cores/pcsx2_libretro.so

# Modify the resolution
sed -i "/^pcsx2_upscale_multiplier =/cpcsx2_upscale_multiplier = \"3\"" ~/.var/app/org.libretro.RetroArch/config/retroarch/config/LRPS2/LRPS2.opt

dbus[2]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file ../../dbus/dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
```

* `timeout 2`... -- succeeds
* `sed -i`... -- fails

**Comment by davidhedlund** [comment]
* https://github.com/flathub/org.libretro.RetroArch/issues/311
