### ISSUE TITLE
Change joypad_autoconfig_dir to "~/.var/.../autoconfig" to make it compatible with `Update Controller Profiles`, and `Save Controller Profile`

### ISSUE THREAD

**Issue by davidhedlund** [flathub/org.libretro.RetroArch#295]
The accessibility and updateability of controller profiles without the need for elevated permissions significantly enhances both the functionality and user experience of the RetroArch Flatpak package. By removing this step, the system becomes more convenient and user-friendly, allowing for smoother controller configuration and a more seamless gaming experience overall.

# Describe the problem
In the default RetroArch configuration file (retroarch.cfg), the joypad autoconfig directory is set to "/app/share/libretro/autoconfig". This path is actually located in the root directory at "/var/lib/flatpak/app/org.libretro.RetroArch/current/active/files/share/libretro/autoconfig". Due to this setting, RetroArch is unable to extract files to this directory.

## Update Controller Profiles
When attempting to update controller profiles through the menu path: `Main Menu -> Online Updater -> Update Controller Profiles`, the operation fails, as shown in the provided image:

![image](https://github.com/flathub/org.libretro.RetroArch/assets/6416073/2d3c286d-d443-4230-ab52-2d00b8961993)

## Save Controller Profile
* Change "Settings -> Drivers -> Controller" to "[linuxraw](https://docs.libretro.com/guides/input-controller-drivers/#linuxraw-controller-driver)".

"Settings -> Inpute -> RetroPad Binds -> Port 1 Controls":
* Change a button with the controller (required for "Save Controller Profile" to work).
* Click on "Save Controller Profile".
* "Error saving controller profile."

![image](https://github.com/libretro/RetroArch/assets/6416073/5ac7875e-5da2-42ed-a30f-ed72da8b24f6)

# Manual solution
I just added this section in our Joypad Auto Configuration guide: https://docs.libretro.com/guides/controller-autoconfiguration/#flatpak-configuration

After making this change, the update process should complete successfully, as demonstrated in the sections below:

## Update Controller Profiles
![image](https://github.com/flathub/org.libretro.RetroArch/assets/6416073/b28f7d55-872f-4f8c-847e-f92537218ba4)

![Screenshot at 2024-07-09 02-48-13](https://github.com/flathub/org.libretro.RetroArch/assets/6416073/c3e9c41a-ce85-4979-964f-70c090c366bd)

## Save Controller Profile
![image](https://github.com/user-attachments/assets/1d77a345-ed60-4933-811a-71d30fb86a1f)

# Development solution
This improvement streamlines the process for users, eliminating the need to follow this step (https://docs.libretro.com/guides/controller-autoconfiguration/#flatpak-configuration) in order to generate autoconfig files for Flatpak users.

## Update configuration file
Modify the retroarch.cfg file to replace the default joypad autoconfig directory path with a user-accessible location:

```
joypad_autoconfig_dir = "/app/share/libretro/autoconfig"
```

Proposed setting:
```
joypad_autoconfig_dir = "~/.var/app/org.libretro.RetroArch/config/retroarch/autoconfig"
```

## Autoconfig file migration
To ensure independence of the `Update Controller Profiles` option for the controllers to work by default, I suggest one of the following solutions:

* System File Utilization: Automatically copying the system autoconfig files from `/app/share/libretro/autoconfig/`  to the newly designated user directory `~/.var/app/org.libretro.RetroArch/config/retroarch/autoconfig` directory
* Pre-packaged Autoconfig Files: Ship the Flatpak package with a curated set of autoconfig files. During installation or first run, these pre-packaged files would be copied to: `~/.var/app/org.libretro.RetroArch/config/retroarch/autoconfig`

The first option leverages existing system files, while the second allows for a more controlled initial set of profiles. Both methods ensure users have access to basic controller profiles without requiring manual updates.

**Comment by davidhedlund** [comment]
* https://github.com/libretro/RetroArch/issues/16222

**Comment by xordspar0** [comment]
Good summary of the problem.

> Automatically copying the system autoconfig files from /app/share/libretro/autoconfig/ to the newly designated user directory ~/.var/app/org.libretro.RetroArch/config/retroarch/autoconfig directory

As discussed in #256, the problem with copying to a user-writable directory is that we lose the ability to keep the bindings that Retroarch ships with up to date. The problem would shift from "I need to change the path to be able to edit" to "I need to delete bindings if I want to update them".

Retroarch likes to solve this problem by dumping all files into the user's config directory, and updating anything is a manual process. Personally I would like it better to keep things separate and have a way of overriding defaults with user config (sort of in the style of [physfs](https://icculus.org/physfs/)), but I don't know if that will catch on.

**Comment by RobLoach** [comment]
The autoconfigs are shipped with the Flatpak, so I would prefer to disable those online updater options if possible.

As xordspar0 mentioned, it would be awesome to be able to have a merged file system to allow custom additions, similar to how Lakka accomplishes it, but I'm not 100% sure that's an option for Flatpak. Easiest way for you to maintain them yourself is to change the directory to your own home folder directory.

**Comment by RobLoach** [comment]
Going to close this. RetorArch ships with the autoconfig files. If you want to change the autoconfig directory on your system to manage it yourself, then feel free to do that in your configs.

**Comment by geekley** [comment]
I've tried to workaround this using symlinks, but it just won't work, as the app just doesn't pick configs outside once it's grouped by folders like sdl2, etc.

The ideal to avoid having to manage updates manually would be to have an upstream change making the local autoconfig folder override the one bundled in the app. And/or a `joypad_autoconfig_override_dir` in the .cfg, so we could have:
```
joypad_autoconfig_dir = "/app/share/libretro/autoconfig"
joypad_autoconfig_override_dir = "~/.var/app/org.libretro.RetroArch/config/retroarch/autoconfig"
```
Is there an issue already suggesting this upstream?

**Comment by RobLoach** [comment]
I'm sure there's been some thought upstream for it. Not sure where those discussions are though. Lakka uses OverlayFS or something to allow mounting the folders in sequence.

**Comment by davidhedlund** [comment]
> Going to close this. RetorArch ships with the autoconfig files. If you want to change the autoconfig directory on your system to manage it yourself, then feel free to do that in your configs.


Users expect that the online updater works. Why not change?:

`joypad_autoconfig_dir = "/app/share/libretro/autoconfig"`

To:

`joypad_autoconfig_dir = "~/.var/app/org.libretro.RetroArch/config/retroarch/autoconfig"`

**Comment by geekley** [comment]
@davidhedlund Because they would also expect `flatpak update` to update the built-in config files whenever a new version of RetroArch comes, without having to worry about doing it manually. This is why the ideal would be to have the "override" dir logic implemented upstream, and adding just your overrides in a separate folder.
