### ISSUE TITLE
Online Updater: Pop-up message sequence error

### ISSUE THREAD

**Issue by davidhedlund** [flathub/org.libretro.RetroArch#297]
## Expected Behavior
The pop-up messages during the update process should appear in the following order, with the last message fading away slowly:
1. "Downloading..."
2. "Extracting..."

It's crucial to confirm that the update process completes both the download and extraction phases, not just the download. The user should be able to verify that the controller profiles are fully updated and ready for use.

### Actual Behavior
The pop-up messages appear in an incorrect sequence:
1. "Downloading..." (displays first)
2. "Extracting..." (appears briefly, almost imperceptible)
4. "Downloading..." (reappears and remains on screen)

See the video to analyze the issue by frame: 
[vokoscreenNG-2024-07-18_14-08-42.webm](https://github.com/user-attachments/assets/1c429cea-d7b9-4910-8d58-702502e775fa)

![image](https://github.com/user-attachments/assets/3c69658a-1f3b-4e2c-8044-df457bf320b1)

### Steps to Reproduce
1. Open RetroArch
2. Navigate to `Main Menu`
3. Select `Online Updater`
5. Choose any `Update ` entry, for example `Update Controller Profiles`

### Environment Information
- Platform: Linux (Flatpak)
- Flatpak Version: 1.19.1

### Additional Notes
- The "Extracting..." message appears only for a fraction of a second, making it easy to miss.
- The final "Downloading..." message persists on screen instead of fading away as expected.

### Bisect Results
[This section needs to be filled in after performing a bisect to determine when the issue was introduced]

### System Information
Please provide any additional relevant system information from RetroArch's Information/System Information menu.

**Comment by RobLoach** [comment]
The Flatpak will be responsible for updating the controller profiles. Periodically, we can update the git commit hash in https://github.com/flathub/org.libretro.RetroArch/blob/master/org.libretro.RetroArch.json .

If anything, we should disable the updater for info files, assets, profiles, cheats, database, overlays, shaders, etc.

**Comment by davidhedlund** [comment]
> If anything, we should disable the updater for info files, assets, profiles, cheats, database, overlays, shaders, etc.

Do you have any idea when this will happen?

**Comment by davidhedlund** [comment]
> If anything, we should disable the updater for info files, assets, profiles, cheats, database, overlays, shaders, etc.

* For RetroArch in for all released? If so where is the issue submitted at https://github.com/libretro/RetroArch/issues ?
* Or just for Flatpak? If so, where is the issue submitted at https://github.com/flathub/org.libretro.RetroArch/issues ?
