### ISSUE TITLE
Cannot Access Mounted Drives

### ISSUE THREAD

**Issue by Saroufim** [flathub/org.libretro.RetroArch#3]
The flatpak bundle's sandbox settings prevent RetroArch from detecting my roms which are mounted on a different drive and have a unique mount point. Is there a way around this other than moving my ROMs where the sandbox can access them?

**Comment by RobLoach** [comment]
[org.libretro.RetroArch.json states --filesystem=home`](https://github.com/flathub/org.libretro.RetroArch/blob/master/org.libretro.RetroArch.json#L16) which gives the Flatpak access to the home directory. Not sure how to grant access elsewhere.

http://flatpak.org/flatpak/flatpak-docs.html

Maybe you could look through and see if there's a way to get at mounted drives?

**Comment by Saroufim** [comment]
Apparently, it's possible to give the sandbox access to the drives by specifying the file path (in example: --filesystem=/mount/drive/games/roms). This workaround fixes but it remains a workaround. I hope that flatpak supports a proper method of changing sandbox access and permissions in the future.

**Comment by RobLoach** [comment]
How do you add that to when running the application through flatpak?

**Comment by Saroufim** [comment]
Flatpak run --filesystem=path org.libretro.RetroArch. if you add that to
the .desktop file, you can just launch it via the app picker.

**Comment by TingPing** [comment]
No need to modify any desktop file: `flatpak override --filesystem=/foo org.libretro.RetroArch`

**Comment by RobLoach** [comment]
Think we should switch to `--filesystem=host` for this image?

**Comment by TingPing** [comment]
It is probably acceptable if not ideal
