### ISSUE TITLE
Using the controller Test feature in RetroArch

### ISSUE THREAD

**Issue by davidhedlund** [flathub/org.libretro.RetroArch#305]
# Instructions

To proceed, please follow these steps:

- Go to: Settings > Drivers > Controller
- Choose "test"
- Restart RetroArch

## Questions

Could you guide me on how to use this feature?

Is it essential for non-development purposes? I'm wondering if regular users might find it a bit distracting.

Additionally, I noticed this option is available in the AppImage version as well, but not in the apt package for Ubuntu.

**Comment by RobLoach** [comment]
The test driver is a driver used for testing. You likely shouldn't use it. People who don't know how to use the Advanced Settings also shouldn't be messing with that stuff anyway.

It's possible to disable it by disazbling `HAVE_TEST_DRIVERS` when compiling. They're helpful for testing, so I'll leave them in.
