### ISSUE TITLE
Access to /media/

### ISSUE THREAD

**Issue by RobLoach** [flathub/org.libretro.RetroArch#31]
From https://github.com/libretro/www.retroarch.com/issues/7 ....  @zayuim

> But I haven't figured out how to access /media/. I can't access this because of something to do with Flatpak right?

**Comment by TingPing** [comment]
Discussed in #3

**Comment by RobLoach** [comment]
Ah, right, thanks.... Maybe we just add documentation about `flatpak run --filesystem=host`

**Comment by TingPing** [comment]
Just make it default, this flatpak doesn't care about sandboxing
