### ISSUE TITLE
Needs a screenshot 

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.libretro.RetroArch#37]
This app needs one or more screenshots added to the appdata, otherwise it looks a bit rubbish in software stores.

https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.howtogeek.com%2Fwp-content%2Fuploads%2F2016%2F06%2Fretroarch-games.png&f=1

https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.JJAXOlscEDKXh8zqsWlMMQHaEK%26pid%3D15.1&f=1

https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.howtogeek.com%2Fwp-content%2Fuploads%2F2016%2F06%2Fretroarch-main.png&f=1

**Comment by LeandroStanger** [comment]
@nedrichards could help

**Comment by RobLoach** [comment]
Another one to the list:
https://github.com/RobLoach/libretro-dolphin-launcher/blob/master/screenshot.jpg

Is there any documentaiton about where in the appdata it would go?

**Comment by LeandroStanger** [comment]
![captura de tela de 2018-02-04 22-00-18](https://user-images.githubusercontent.com/26097419/35783903-003f238a-09f7-11e8-9c09-a57cc91f406e.png)

**Comment by TingPing** [comment]
@RobLoach Documented here: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#sect-Metadata-GenericComponent

Example: https://github.com/flathub/com.discordapp.Discord/blob/master/com.discordapp.Discord.appdata.xml#L14-L23

**Comment by RobLoach** [comment]
@LeandroStanger Thoughts on https://github.com/flathub/org.libretro.RetroArch/pull/39 ?
