### ISSUE TITLE
Simplify release notes

### ISSUE THREAD

**Issue by TingPing** [flathub/org.libretro.RetroArch#45]
The [current release notes](https://github.com/flathub/org.libretro.RetroArch/blob/ec90d91efa99c0fa58a11b425d3e3f5bcf81b78d/org.libretro.RetroArch.appdata.xml#L27-L88) are very long and technical.

The purpose of the release notes is for end users to read and see what has changed. These aren't really quite as useful for that purpose and read more like a commit log. Some of them are especially useless given the context that this information is for Linux only so the many lines talking about other platforms are just noise.

**Comment by RobLoach** [comment]
> These release-notes should contain brief information about what is new in the release, in a way which is understandable by non-technical users.

Definitely need to simplify the release notes. The summaries on the blog post may be worth considering, but those are published after the release cycle.

**Comment by RobLoach** [comment]
I believe these hath been simplificationed. Let me know if you'd enjoy simpler of the cleanings. :rocket:
