### ISSUE TITLE
Cg Licensing

### ISSUE THREAD

**Issue by RobLoach** [flathub/org.libretro.RetroArch#52]
http://developer.download.nvidia.com/cg/Cg_2.2/license.pdf

Should we remove it?

**Comment by TingPing** [comment]
So reading the license it seems we are totally able to distribute it so that is fine. I think if you want to keep it though you should probably add the proprietary license to the appdata file though.

**Comment by RobLoach** [comment]
Seems fine! Thanks for the check.
