### ISSUE TITLE
Add WIMP Qt interface

### ISSUE THREAD

**Issue by RobLoach** [flathub/org.libretro.RetroArch#56]
Compile with Qt5 to allow using the WIMP interface.

## References

- Pull Request: https://github.com/flathub/org.libretro.RetroArch/pull/71

**Comment by RobLoach** [comment]
Yeah, I haven't used it yet myself. Haven't really had the need so far. Glad it worked here!

**Comment by maci0** [comment]
+1

**Comment by RobLoach** [comment]
There's a Pull Request up for this over at https://github.com/flathub/org.libretro.RetroArch/pull/71 . It proposes moving over to the KDE Runtime, which may be a good option.

Feedback appreciated!
