### ISSUE TITLE
Core Reicast OIT does not appear to download in Flatpak.

### ISSUE THREAD

**Issue by alexb3d** [flathub/org.libretro.RetroArch#63]
Hi. Reicast OIT does not appear in "Core Updater" for Flatpak.

**Comment by RobLoach** [comment]
![screenshot at 2018-06-16 17-09-39](https://user-images.githubusercontent.com/25086/41502449-23b202da-7188-11e8-8a92-2c4336e624a3.png)

It should be listed as `reicast_oit_libretro.so.zip`.... Haven't updated the .nfo files yet. Thanks for the note on that.

**Comment by alexb3d** [comment]
Ok, I see it with that name, thank you.

**Comment by RobLoach** [comment]
Hope we can update the .nfo files soon so that it appears with the right name :+1:  Thanks a lot.
