### ISSUE TITLE
"Failed to open libretro core"

### ISSUE THREAD

**Issue by Heryhelder** [flathub/org.libretro.RetroArch#81]
S.O: Fedora 28
RetroArch version: 1.7.4
Nightly cores.

I'm trying to use dolphin core to play and it always show me the same error "failed to open libretro core". PSx core runs fine.

It's a fresh install of retroarch using flatpak.

Here are some logs:
[https://pastebin.com/Yz99PA1U](url)

It runs fine if i compile source code of RetroArch.

How can i solve this?

**Comment by Heryhelder** [comment]
[https://pastebin.com/x0pjPQqM](url)
It seems to be related to libudev.

**Comment by Heryhelder** [comment]
[https://pastebin.com/x0pjPQqM](url)

it seems to be related to libudev

**Comment by Heryhelder** [comment]
Same here.

**Comment by Spudd86** [comment]
It seems that RetroArch is being build against a different libudev version in flatpak than the one the Dolphin core is linked to.

I the flatpak of RetroArch it includes a libudev.so.0 and libudev.so.0.13.0 but the Dolphin core wants to link to libudev.so.1 so the ABI version is different.

It seems like the fix would be to update the version of libudev used when building the RetroArch flatpak.

**Comment by Spudd86** [comment]
So I have tried building a new flat pack with udev replaced with Gentoo's eudev package and now Dolphin fails to load because it's missing libusb

**Comment by Spudd86** [comment]
Switching to eudev 3.2.7 as a provider of libudev and adding libusb does seem to fix the issue.

Using these as modules and NOT using the normal udev-175 module in the RetroArch build should fix this issue.

[eudev-3.2.7.json.txt](https://github.com/flathub/org.libretro.RetroArch/files/2579041/eudev-3.2.7.json.txt)
[libusb-1.0.22.json.txt](https://github.com/flathub/org.libretro.RetroArch/files/2579044/libusb-1.0.22.json.txt)

**Comment by Exalm** [comment]
Another core, another library:
```
[ERROR] Failed to open libretro core: "/home/exalm/.var/app/org.libretro.RetroArch/config/retroarch/cores/parallel_n64_libretro.so"
[ERROR] Error(s): libtinfo.so.5: cannot open shared object file: No such file or directory
```

**Comment by soredake** [comment]
PPSSPP works fine.

**Comment by soredake** [comment]
parallel-n64 and mupen64-plus too.

**Comment by soredake** [comment]
Dolphin too, but crashes when using "gl" driver, works fine on vulkan.
```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  26 (X_GLXMakeContextCurrent)
  Serial number of failed request:  68
  Current serial number in output stream:  68
```

**Comment by RobLoach** [comment]
I believe building the cores in as part of the Flatpak would solve a lot of these issues... https://github.com/flathub/org.libretro.RetroArch/issues/243
