### ISSUE TITLE
Recording doesn't work

### ISSUE THREAD

**Issue by tpimh** [flathub/org.libretro.RetroArch#90]
I'm using retroarch flatpak with default settings and when I choose "Start Recording", the menu closes, but nothing happens.

**Comment by RobLoach** [comment]
Do you find anything in the log? May be missing ffmpeg or something.

**Comment by tpimh** [comment]
Where can I find the log? If I run it with `flatpak run org.libretro.RetroArch` nothing related to this issue is printed.

**Comment by RobLoach** [comment]
Should be something like......

```
flatpak run org.libretro.RetroArch --verbose
```

**Comment by laamaa** [comment]
It seems to be due to libx264 not being found by ffmpeg. With the default settings, the logs say:

[ERROR] [FFmpeg]: Cannot find vcodec libx264.

Changing the codec to WebM from main settings works.

**Comment by RobLoach** [comment]
@laamaa Can you find the setting in the config? We can set it in https://github.com/flathub/org.libretro.RetroArch/blob/master/retroarch.cfg

**Comment by laamaa** [comment]
`video_record_quality = "6"`

this sets the profile to "WebM High Quality"
