### ISSUE TITLE
unable to start retroarch with nvidia legacy drivers

### ISSUE THREAD

**Issue by ashak** [flathub/org.libretro.RetroArch#91]
Ok,

I've been trying to setup retroarch via flatpak install on a Debian testing system. It's a standard 'debian desktop environment' install giving me Gnome. I've installed the package that contains the nvidia drivers for the graphics card in the system (nvidia-legacy-340xx-driver). I installed retroarch using flatpak exactly as described on the retroarch website. But I am unable to start retroarch.

If I add a -v to the flatpak run command, I get this output:

> $ flatpak -v run org.libretro.RetroArch
> F: No installations directory in /etc/flatpak/installations.d. Skipping
> F: Opening user flatpak installation at path /home/user/.local/share/flatpak
> F: Opening system flatpak installation at path /var/lib/flatpak
> F: Opening user flatpak installation at path /home/user/.local/share/flatpak
> F: Opening user flatpak installation at path /home/user/.local/share/flatpak
> F: Cleaning up unused container id 1361581282
> F: Allocated instance id 633993167
> F: Allowing host-fs access
> F: Allowing wayland access
> F: Allowing x11 access
> F: Allowing pulseaudio access
> F: Pulseaudio user configuration file '/home/user/.config/pulse/client.conf': Error opening file /home/user/.config/pulse/client.conf: No such file or directory
> F: Failed to run in transient scope: In WaitingForReject: Expected 'REJECTED am1 am2 ... amN', got 'ERROR'
> F: Running 'bwrap --args 32 /usr/libexec/flatpak-dbus-proxy --args=34'
> F: Running 'bwrap --args 29 retroarch'
> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast
> libEGL warning: DRI2: failed to authenticate

Since the failure seemed to be libGL related, i've used LIBGL_DEBUG=true in the past to get more useful output... So if I prefix the flatpak run command with that, I get the following output

> $ LIBGL_DEBUG=true flatpak run org.libretro.RetroArch
> libGL: screen 0 does not appear to be DRI2 capable
> libGL: OpenDriver: trying /lib/dri/tls/swrast_dri.so
> libGL: OpenDriver: trying /lib/dri/swrast_dri.so
> libGL: Can't open configuration file /home/user/.drirc: No such file or directory.
> libGL: Can't open configuration file /home/user/.drirc: No such file or directory.
> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast
> libEGL warning: DRI2: failed to authenticate
> libGL: Can't open configuration file /home/user/.drirc: No such file or directory.
> libGL: Can't open configuration file /home/user/.drirc: No such file or directory.

I thought perhaps GL things were broken on the system, but glxgears runs fine. So I can only assume there's some oddity between how flatpak is doing it and how the system itself does it.

**Comment by TingPing** [comment]
Whats the exact version: `flatpak --gl-drivers`

**Comment by ashak** [comment]
$ flatpak --gl-drivers
nvidia-340-107
default
host

**Comment by TingPing** [comment]
Hmm that version is packaged, can you insure `org.freedesktop.Platform.GL.nvidia-340-107` is installed?

**Comment by ashak** [comment]
I think so:
> $ flatpak list 
> Ref                                                   Options     
> org.libretro.RetroArch/x86_64/stable                  user,current
> org.freedesktop.Platform.GL.nvidia-340-107/x86_64/1.4 user,runtime
> org.freedesktop.Platform.ffmpeg/x86_64/1.6            user,runtime
> org.kde.KStyle.Adwaita/x86_64/5.11                    user,runtime
> org.kde.Platform/x86_64/5.11                          user,runtime
>

**Comment by TingPing** [comment]
If anything its a bug in how the nvidia driver is packaged for flatpak, I don't think anybody else really had such old hardware to test with.

**Comment by TingPing** [comment]
@ashak 	You can try:

```
flatpak install flathub org.freedesktop.GlxInfo//18.08
flatpak run org.freedesktop.GlxInfo//18.08
```

If it fails its a driver issue.

**Comment by ashak** [comment]
Is there anything else I can do in relation to this?

**Comment by TingPing** [comment]
That output makes it look like everything is working fine so I'm not sure.

**Comment by ashak** [comment]
If it's any help, I tried a few other flatpaked things, supertuxkart and something else... Both of which seemed to work fine.

**Comment by ashak** [comment]
@RobLoach I don't think it's possible to do Vulkan with the legacy nVidia drivers?

**Comment by ashak** [comment]
Hrm, I appear to have been wasting peoples time. I just reinstalled this machine, Installed the nVidia legacy drivers, rebooted, installed flatpak, install retroarch via flapak, run retroarch via flatpak and it seems to work totally fine. I have no idea what was different with the previous installation, in theory it was installed exactly the same way as i've just reinstalled it.

Apologies to those that have taken the time to look at this issue for me.
